### ISSUE TITLE
Always get Missing package product 'WalletConnect' error when try to run example code

### ISSUE THREAD

**Issue by Santiago0412** [WalletConnect/WalletConnectSwiftV2#189]
**Describe the bug**
Download the example code

**SDK Version**
 - Client: Xcode 
 - Version 13.3.1

**To Reproduce**
1. Download the example code
2. Build
3. Get _Missing package product 'WalletConnect' error_ 
4. I try to build _WalletConnect_ scheme, succeed, but get another error: _Missing package product 'Web3'_

**Expected behavior**
Example code works

**Screenshots**
<img width="271" alt="image" src="https://user-images.githubusercontent.com/10152008/166617289-a929e9f3-b801-4794-8cee-6953e0310154.png">

**Device (please complete the following information):**
 - Device: iPhone13 simulator

**Comment by llbartekll** [comment]
try File->Packages->reset package cache

**Comment by Santiago0412** [comment]
> try File->Packages->reset package cache

Still have same error when try to build _wallet_ and _dapps_, another change I notice is when I try to build _WalletConnect_ lib it looks like this, can't choose any device to build.
<img width="743" alt="image" src="https://user-images.githubusercontent.com/10152008/166657119-5c00b04e-e828-44d2-b39f-15afb5ab49b7.png">

**Comment by llbartekll** [comment]
Do you open ExampleApp.xcodeproj or WalletConnectSwiftV2 Package? if you want to build sample app you need to open `ExampleApp.xcodeproj`.

**Comment by hirad** [comment]
I have the same issue. Opening `ExampleApp.xcodeproj`.

**Comment by Santiago0412** [comment]
> 

Sure, there is only one xcodeproj file, so I just opened `ExampleApp.xcodeproj`

**Comment by Droppix** [comment]
+1 same error

**Comment by MisterVants** [comment]
It should be fixed now on `main` branch. 

Before building, also try resetting the package caches by going "File > Packages > Reset Package Caches" on Xcode.

**Comment by kevinwo** [comment]
This is still an issue on main. I did a fresh clone, resolved package dependencies, built, encountered error. I cleaned, cleared package cache as mentioned here, built, and still encounter the error.
