### ISSUE TITLE
[Crash] SDK crashes when disconnect from topic

### ISSUE THREAD

**Issue by lmcmz** [WalletConnect/WalletConnectSwiftV2#596]
**Describe the bug**
When disconnecting from topic, SDK crashes sometime.

```
WalletConnectNetworking/NetworkingInteractor.swift:98: Fatal error: 'try!' expression unexpectedly raised an error: WalletConnectKMS.Serializer.Errors.symmetricKeyForTopicNotFound
2022-11-17 07:59:43.276879+1100 Dapper Pro[40117:9253430] WalletConnectNetworking/NetworkingInteractor.swift:98: Fatal error: 'try!' expression unexpectedly raised an error: WalletConnectKMS.Serializer.Errors.symmetricKeyForTopicNotFound
```

**SDK Version**
 - Client: Swift
 - Version: 1.0.5

**To Reproduce**
1. Go to a dApp
2. Make a connection
3. Disconnect from the topic
4. Disconnect again from the topic

**Expected behavior**
The pairing or session need to be removed from the list

**Screenshots**
<img width="1034" alt="Screenshot 2022-11-17 at 8 00 25 am" src="https://user-images.githubusercontent.com/9669733/202293374-fa11c064-9882-42f9-8bcc-625c20062a8a.png">

**Device:**
 - Device: iPhone12 Pro Max
 - OS:  iOS16

**Comment by llbartekll** [comment]
> 3. Disconnect from the topic
> 4. Disconnect again from the topic

Hey @lmcmz why do you disconnect from the same topic twice?

**Comment by lmcmz** [comment]
Hey @llbartekll, 

After we disconnect from the topic, it seem like it will still stay in the list of settled session -> ` Sign.instance.getSessions()`.
Which cause the disconnect twice, user got confused, since first disconnect won't remove it from the list then it got crash.

**Comment by llbartekll** [comment]
do you subscribe to `sessionDeletePublisher`?

**Comment by lmcmz** [comment]
Yes, it happens in my project. Somehow, some sessions in the list can't be disconnected, and it keeps in the list (Sign.instance.getSessions).

**Comment by llbartekll** [comment]
ok but does `sessionDeletePublisher` publish when you call `disconnect()` with the first time?

**Comment by llbartekll** [comment]
btw. does disconnect() throws an error when you call it with the first time?

**Comment by lmcmz** [comment]
I will keep an eye on it. But I do reproduce the disconnect crash frequently, it's kinda annoying since some of the connections will never be able to disconnect.

is there a quick fix that we should remove the force `try!` in any place in the SDK ?

**Comment by llbartekll** [comment]
hey, the crash is fixed, we will release a new version tomorrow so you can upgrade.

> it's kinda annoying since some of the connections will never be able to disconnect.

I think it won't happen. I believe you were calling a function twice and there were keys removed after a second call, so function did not throw immediately and tried to remove a keys with the second call too. Now it will just throw an error.

**Comment by llbartekll** [comment]
if you like you can test on develop branch already

**Comment by lmcmz** [comment]
Hey @llbartekll,
Thanks for the fix, it's not crashing. 
But the disconnect issue is still persistent, after the wallet sends deleting request, the connection is still in the session list.

From what I observed the sessionDeletePublisher is not triggering for the first time.
but the dApp has received for the deletion request
> EVENT pairing_delete {id: 1669726832666843, topic: 'fd0c42600f03f55e18f193eaf985380e06903283d6936602b743e255bc6486ae'}

**Comment by lmcmz** [comment]
It seem like there is some different behavior between `Sign.instance.disconnect` and `Pair.instance.disconnect`.
Mainly, I can reproduce it with  `Pair.instance`.

**Comment by llbartekll** [comment]
@lmcmz 

> But the disconnect issue is still persistent, after the wallet sends deleting request, the connection is still in the session list.

 ```try await Sign.instance.disconnect
//here the session has already disappeared ```

the function is async and if it not throws and will return it means that the session has been removed, so you can querry sessions and update your list

> It seem like there is some different behavior between Sign.instance.disconnect and Pair.instance.disconnect.

it is different behaviour because `Pair.instance.disconnect` disconnects pairings not sessions, those are two different object types

**Comment by llbartekll** [comment]
@lmcmz can we cole the issue?

**Comment by lmcmz** [comment]
Yeah, let's close it for now. 
I will re-open it, once I meet it again.
